/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.administrativo.telas;


import javax.swing.JFrame;
import br.edu.imepac.agendamento.telas.CadastroConsulta;
/**
 *
 * @author ALUNO
 */
public class Atendente extends javax.swing.JFrame {

    /**
     * Creates new form Atendente
     */
    public Atendente() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VisConsulta = new javax.swing.JButton();
        CadConsulta = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nomeCLinica = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        bemVindo = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        imgIcon = new javax.swing.JLabel();
        GerPaciente = new javax.swing.JLabel();
        btnAgendConsulta = new javax.swing.JButton();
        btnListConsulta = new javax.swing.JButton();
        GerConsulta = new javax.swing.JLabel();
        btnCadPaciente = new javax.swing.JButton();
        btnListPaciente = new javax.swing.JButton();
        btnCadastroConv = new javax.swing.JButton();
        btnVerConve = new javax.swing.JButton();

        VisConsulta.setBackground(new java.awt.Color(51, 51, 51));
        VisConsulta.setForeground(new java.awt.Color(255, 255, 255));
        VisConsulta.setText("Visualizar Consulta");
        VisConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisConsultaActionPerformed(evt);
            }
        });

        CadConsulta.setBackground(new java.awt.Color(51, 51, 51));
        CadConsulta.setForeground(new java.awt.Color(255, 255, 255));
        CadConsulta.setText("Cadastrar Consulta");
        CadConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadConsultaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        nomeCLinica.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nomeCLinica.setText("MedClinical");

        logout.setBackground(new java.awt.Color(102, 102, 102));
        logout.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        logout.setText("LOGOUT");
        logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        bemVindo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bemVindo.setText("Bem - Vindo(a) ,");

        usuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usuario.setText("usuário");

        imgIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\mateu\\OneDrive\\Área de Trabalho\\imgsProjeto\\IconProjeto.png")); // NOI18N

        GerPaciente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GerPaciente.setText("Gerenciar pacientes");

        btnAgendConsulta.setBackground(new java.awt.Color(51, 51, 51));
        btnAgendConsulta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgendConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnAgendConsulta.setText("Agendar consulta");
        btnAgendConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendConsultaActionPerformed(evt);
            }
        });

        btnListConsulta.setBackground(new java.awt.Color(51, 51, 51));
        btnListConsulta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListConsulta.setForeground(new java.awt.Color(255, 255, 255));
        btnListConsulta.setText("Lista de Consultas");
        btnListConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListConsultaActionPerformed(evt);
            }
        });

        GerConsulta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GerConsulta.setText("Gerenciar consultas");

        btnCadPaciente.setBackground(new java.awt.Color(51, 51, 51));
        btnCadPaciente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnCadPaciente.setText("Cadastrar pacientes");
        btnCadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadPacienteActionPerformed(evt);
            }
        });

        btnListPaciente.setBackground(new java.awt.Color(51, 51, 51));
        btnListPaciente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnListPaciente.setText("Lista de pacientes");
        btnListPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListPacienteActionPerformed(evt);
            }
        });

        btnCadastroConv.setBackground(new java.awt.Color(51, 51, 51));
        btnCadastroConv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastroConv.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastroConv.setText("Cadastro Convênio");
        btnCadastroConv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroConvActionPerformed(evt);
            }
        });

        btnVerConve.setBackground(new java.awt.Color(51, 51, 51));
        btnVerConve.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerConve.setForeground(new java.awt.Color(255, 255, 255));
        btnVerConve.setText("Visualizar convênio");
        btnVerConve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerConveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GerConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCadastroConv)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnListConsulta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(btnAgendConsulta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnListPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(btnVerConve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(imgIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeCLinica)
                                .addGap(103, 103, 103)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(bemVindo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(usuario))
                                    .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(GerPaciente)
                            .addComponent(btnCadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bemVindo)
                            .addComponent(usuario)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imgIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(nomeCLinica)))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GerConsulta)
                    .addComponent(GerPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgendConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastroConv, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerConve, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadConsultaActionPerformed
      
    }//GEN-LAST:event_CadConsultaActionPerformed

    private void VisConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisConsultaActionPerformed
       
    }//GEN-LAST:event_VisConsultaActionPerformed

    private void btnListConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListConsultaActionPerformed
       this.dispose();
       ListaConsulta listaConsulta = new ListaConsulta();
       listaConsulta.setVisible(true);
    }//GEN-LAST:event_btnListConsultaActionPerformed

    private void btnCadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadPacienteActionPerformed
       this.dispose();
       CadastroPaciente CadPaciente = new CadastroPaciente();
       CadPaciente.setVisible(true);
    }//GEN-LAST:event_btnCadPacienteActionPerformed

    private void btnListPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListPacienteActionPerformed
       this.dispose();
        ListaPaciente listaPaciente = new ListaPaciente();
        listaPaciente.setVisible(true);
    }//GEN-LAST:event_btnListPacienteActionPerformed

    private void btnCadastroConvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroConvActionPerformed
       this.dispose();
       Convenio CadConvenio = new Convenio();
       CadConvenio.setVisible(true);
    }//GEN-LAST:event_btnCadastroConvActionPerformed

    private void btnVerConveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerConveActionPerformed
       this.dispose();
       ListaConvenios listaConvenio = new ListaConvenios();
       listaConvenio.setVisible(true);
    }//GEN-LAST:event_btnVerConveActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        this.dispose();
        TelaHome telaLogin = new TelaHome();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void btnAgendConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendConsultaActionPerformed
        this.dispose();
        CadastroConsulta cadastroConsulta = new CadastroConsulta();
        cadastroConsulta.setVisible(true);
    }//GEN-LAST:event_btnAgendConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Atendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Atendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Atendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Atendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Atendente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadConsulta;
    private javax.swing.JLabel GerConsulta;
    private javax.swing.JLabel GerPaciente;
    private javax.swing.JButton VisConsulta;
    private javax.swing.JLabel bemVindo;
    private javax.swing.JButton btnAgendConsulta;
    private javax.swing.JButton btnCadPaciente;
    private javax.swing.JButton btnCadastroConv;
    private javax.swing.JButton btnListConsulta;
    private javax.swing.JButton btnListPaciente;
    private javax.swing.JButton btnVerConve;
    private javax.swing.JLabel imgIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JLabel nomeCLinica;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
